### ISSUE TITLE
Create Alignment abstraction (4 days)

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/toolkit-v2#4]
Description:
Given two stem opf path to the repo or opf_id of the repo, Need to create OPA using the given data.

Completion Criteria:
When pipeline to create the OPA is ready with the test passed.

Openpecha Alignment Structure:
```
pecha_id
- pecha_id.opf
     - meta.json
     - DA11.json
```
Pecha's Meta Attributes:
```
id: str
title: list[str]
author: list[str]
created_at: datetime
source: str
source_metadata: dict
alignment_to_base:
  Root_opf/base_name: Alignment_name
  Commentary_opf/base_name: Alignment_name
```

Subtasks:
- [ ] Write the tests
- [ ] Write segment pair
- [ ] Read segment pairs
- [ ] Write metadata
